# Generated by Django 5.2.3 on 2025-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('user', 'user'), ('guest', 'guest')], default='user', max_length=10),
        ),
    ]
